import { ROLES } from "./role";

const PERMISSIONS = {
  STUDENTS: {
    VIEW: "view_students",
    ADD: "add_student",
    EDIT: "edit_student",
    REMOVE: "remove_student",
  },
  ATTENDANCE: {
    VIEW: "view_attendance",
    EDIT: "edit_attendance",
  },
  REPORTS: {
    VIEW: "view_reports",
    EXPORT: "export_reports",
  },
  DEPARTMENTS: {
    VIEW: "view_departments",
    MANAGE: "manage_departments",
  },
};

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.STUDENTS.VIEW, PERMISSIONS.STUDENTS.ADD, PERMISSIONS.STUDENTS.EDIT, PERMISSIONS.STUDENTS.REMOVE,
    PERMISSIONS.ATTENDANCE.VIEW, PERMISSIONS.ATTENDANCE.EDIT,
    PERMISSIONS.REPORTS.VIEW, PERMISSIONS.REPORTS.EXPORT,
    PERMISSIONS.DEPARTMENTS.VIEW, PERMISSIONS.DEPARTMENTS.MANAGE,
  ],
  [ROLES.TEACHER]: [
    PERMISSIONS.STUDENTS.VIEW,
    PERMISSIONS.ATTENDANCE.VIEW, PERMISSIONS.ATTENDANCE.EDIT,
    PERMISSIONS.REPORTS.VIEW,
    PERMISSIONS.DEPARTMENTS.VIEW,
  ],
  [ROLES.STUDENT]: [
    PERMISSIONS.ATTENDANCE.VIEW,
  ],
};

export { PERMISSIONS, ROLE_PERMISSIONS };
